spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri : http://localhost:8181/
          predicates:
            - Path= /customers/**
        - id : r2
          uri : http://localhost:8282/
          predicates:
            - Path= /products/**

